{
 "title": "FastAPI Metrics.",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Error rate %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 * (\r\n  sum(rate(api_requests_total{status=~\"5..\"}[5m])) /\r\n  sum(rate(api_requests_total[5m]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errores 5xx / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(api_errors_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latencia P95 por endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, endpoint) (rate(api_request_duration_seconds_bucket[5m]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS por status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (status) (rate(api_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS por endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(api_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}