route:
  receiver: slack
  group_by: ['alertname','instance']
  group_wait: 10s
  group_interval: 2m
  repeat_interval: 4h


receivers:
  - name: slack
    slack_configs:
      - api_url_file: /run/secrets/slack_webhook_url
        channel: "#alerts"
        send_resolved: true
        title: '{{ .CommonLabels.alertname }} — {{ .CommonLabels.instance }} ({{ .Status }})'
        text: >
          *Alert:* {{ .CommonLabels.alertname }}
          *Severity:* {{ .CommonLabels.severity }}
          *Instance:* {{ .CommonLabels.instance }}
          *Description:* {{ .CommonAnnotations.description }}