global:
  scrape_interval: 15s # Default scrape interval.
  evaluation_interval: 15s # Default evaluation interval.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'api_metrics'
    metrics_path: /metrics   
    static_configs:
      - targets: ['api:8000'] # Replace 'api:8000' with your actual API service name and port
  
      