groups:
  - name: infra.node
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels: { severity: "critical" }
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."

      - alert: HighCPUUsage
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[1m])) * 100) > 80
        for: 5m
        labels: { severity: "warning" }
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is above 80% for more than 5 minutes."

      - alert: DiskAlmostFull
        expr: (node_filesystem_avail_bytes{fstype!~"tmpfs|overlay|squashfs",mountpoint!~"^/(run|var/lib/docker)($|/)"} / node_filesystem_size_bytes{fstype!~"tmpfs|overlay|squashfs",mountpoint!~"^/(run|var/lib/docker)($|/)"}) < 0.15
        for: 10m
        labels: { severity: "warning" }
        annotations:
          summary: "Disk space almost full on {{ $labels.instance }}"
          description: "Free space < 15% for more than 10 minutes."

  - name: app.fastapi
    rules:
    - alert: FastAPI5xxRate
      expr: (
               sum by (instance) (rate(api_errors_total[5m])) 
               /
               sum by (instance) (rate(api_requests_total[5m]))
            ) * 100 > 5
      for: 30s
      labels: { severity: "critical" }
      annotations:
        summary: "High rate of 5xx errors on {{ $labels.instance }}"
        description: "5xx > 5% (5m) for more than 30s."

  - name: db.postgres
    rules:
      - alert: PostgresDown
        expr: pg_up == 0
        for: 1m
        labels: { severity: "critical" }
        annotations:
          summary: "Postgres instance {{ $labels.instance }} down"
          description: "Postgres instance {{ $labels.instance }} has been down for more than 1 minute."

      - alert: HighDBConnections
        expr: pg_stat_activity_count > 90
        for: 5m
        labels: { severity: "warning" }
        annotations:
          summary: "High number of DB connections on {{ $labels.instance }}"
          description: "The number of active DB connections is above 90 for more than 5 minutes."
