name: CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-linux:
    name: End-to-End (Docker Compose)
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare env and dummy secrets
        run: |
          set -euo pipefail
          mkdir -p alertmanager
          # Webhook dummy (no parece real, no dispara secret scanning)
          echo "DUMMY_WEBHOOK" > alertmanager/slack_webhook_url

          # Crea .env solo si no existe (forma segura, sin if/fi que rompe con heredoc)
          [ -f .env ] || cat > .env <<'EOF'
          PROMETHEUS_URL=http://localhost:9090
          GRAFANA_URL=http://localhost:3000
          ALERTMANAGER_URL=http://localhost:9093
          GRAFANA_ADMIN_USER=admin
          GRAFANA_ADMIN_PASSWORD=admin
          EOF


      - name: Show versions
        run: |
          docker --version
          docker compose version
          bash --version
          pwsh --version

      - name: Build & Start (Compose)
        run: |
          docker compose -f docker-compose.yml -p grafana-prometheus-stack up -d --remove-orphans

      - name: Smoke Validation (PowerShell)
        shell: pwsh
        run: |
          ./validate.ps1 -Retries 60 -SleepSecs 5

      - name: Compose PS
        if: always()
        run: docker compose -f docker-compose.yml -p grafana-prometheus-stack ps

      - name: Collect Logs on failure
        if: failure()
        run: |
          docker compose -f docker-compose.yml -p grafana-prometheus-stack logs --no-color > compose.log || true

      - name: Upload Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: compose-logs
          path: compose.log

      - name: Down stack
        if: always()
        run: |
          docker compose -f docker-compose.yml -p grafana-prometheus-stack down -v
